apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: memory
  labels:
    app.kubernetes.io/name: memory
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: memory
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
