apiVersion: v1
kind: ServiceAccount
metadata:
  name: memory
  labels:
    app.kubernetes.io/name: memory
  annotations:
    azure.workload.identity/client-id: "<set by overlay>"
    azure.workload.identity/tenant-id: "<set by overlay>"
