apiVersion: v1
kind: Service
metadata:
  name: memory
  labels:
    app.kubernetes.io/name: memory
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: memory
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
